name: Coverage

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  
jobs:
  coverage:
    name: Generate coverage report
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/checkout@v1
        with:
          node-version: 11.x
      - name: Run tests
        run: yarn install
        run: yarn package:test:coverage

